/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as battleshipsSol from "./Battleships.sol";
export type { battleshipsSol };
import type * as simpleSol from "./Simple.sol";
export type { simpleSol };
export type { FHECounter } from "./FHECounter";
