/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Battleships__factory } from "./Battleships__factory";
export { Test__factory } from "./Test__factory";
